### ISSUE TITLE
Pyload: undefined symbol: SSLv2_client_method

### ISSUE THREAD

**Issue by lorimz** [Entware-ng/Entware-ng#220]
Hello, today I ran opkg update && opkg upgrade and it downloaded among other packages a new pyload version (0.4.9-20160307-2) but when I try to restart it this is the output:
```bash
[~] # /opt/etc/init.d/S51pyload start
starting pyLoad
Traceback (most recent call last):
  File "/opt/bin/pyload", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/share/CACHEDEV1_DATA/.qpkg/Entware-ng/share/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/share/CACHEDEV1_DATA/.qpkg/Entware-ng/share/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/share/CACHEDEV1_DATA/.qpkg/Entware-ng/share/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: /opt/lib/libcurl.so.4: undefined symbol: SSLv2_client_method
[~] #
```
and pyload doesn't start.

**Comment by zyxmon** [comment]
Try to `opkg install --force-reinstall libcurl`

**Comment by lorimz** [comment]
this solved the issue
Thanks a lot!
