### ISSUE TITLE
pyexpat.cpython-35.so: undefined symbol: XML_SetCommentHandler

### ISSUE THREAD

**Issue by nklmilojevic** [Entware-ng/Entware-ng#485]
Hi,

i installed python3 and python3-pip with clean install on QNAP (x64).

I'm getting this error:

# pip3
Traceback (most recent call last):
  File "/opt/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 34, in <module>
    import plistlib
  File "/opt/lib/python3.5/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/opt/lib/python3.5/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /opt/lib/python3.5/lib-dynload/pyexpat.cpython-35.so: undefined symbol: XML_SetCommentHandler

Does anyone have an idea what is causing this?

**Comment by nklmilojevic** [comment]
I just found out that pyexpat.cpython-35.so needs linux-vdso

[/opt/lib/python3.5/lib-dynload] # ldd /opt/lib/python3.5/lib-dynload/pyexpat.cpython-35.so
	linux-vdso.so.1 =>  (0x00007fffcf994000)
	libpython3.5.so.1.0 => /opt/lib/libpython3.5.so.1.0 (0x00007f3827cdb000)
	libc.so.6 => /opt/lib/libc.so.6 (0x00007f382793c000)
	libz.so.1 => /opt/lib/libz.so.1 (0x00007f3827726000)
	libpthread.so.0 => /opt/lib/libpthread.so.0 (0x00007f3827508000)
	libdl.so.2 => /opt/lib/libdl.so.2 (0x00007f3827304000)
	libutil.so.1 => /opt/lib/libutil.so.1 (0x00007f3827100000)
	libm.so.6 => /opt/lib/libm.so.6 (0x00007f3826dfa000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f38283d4000)

**Comment by nklmilojevic** [comment]
Also, I installed gcc and the error message got bigger:

[~] # pip3
Traceback (most recent call last):
  File "/opt/bin/pip3", line 11, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip3.5')()
  File "/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2598, in load_entry_point
    return ep.load()
  File "/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2258, in load
    return self.resolve()
  File "/opt/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/lib/python3.5/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/opt/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/opt/lib/python3.5/site-packages/pip/download.py", line 48, in <module>
    from pip._vendor.six.moves import xmlrpc_client
  File "/opt/lib/python3.5/site-packages/pip/_vendor/six.py", line 92, in __get__
    result = self._resolve()
  File "/opt/lib/python3.5/site-packages/pip/_vendor/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/opt/lib/python3.5/site-packages/pip/_vendor/six.py", line 82, in _import_module
    __import__(name)
  File "/opt/lib/python3.5/xmlrpc/client.py", line 137, in <module>
    from xml.parsers import expat
  File "/opt/lib/python3.5/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /opt/lib/python3.5/lib-dynload/pyexpat.cpython-35.so: undefined symbol: XML_SetCommentHandler

**Comment by zyxmon** [comment]
This bug is confirmed. Manually downgrading python3-xml package from archive folder solves this problem. I hope the fix will be soon found.

**Comment by zyxmon** [comment]
fixed in https://github.com/Entware-ng/entware-packages/commit/c8ef1f4c74b33e7b07f49401c15c56abe578ab9b

binaries will be available soon.
