### ISSUE TITLE
deluge web daemon problem

### ISSUE THREAD

**Issue by papampi** [Entware-ng/Entware-ng#514]
Suddenly I cant connect to my deluge web ui and connection manager wont start daemon
tried to restart web with 
```
[~] # /share/CACHEDEV1_DATA/.qpkg/Entware-ng/etc/init.d/S81deluge-web restart
```
but then when I click start daemon on connection manager I get this error 
```
 
[~] # [ERROR   ] 11:59:56 main:245 libboost_system.so.1.62.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Entware-ng/lib/python2.7/site-packages/deluge/main.py", line 238, in start_daemon
    Daemon(options, args)
  File "/share/CACHEDEV1_DATA/.qpkg/Entware-ng/lib/python2.7/site-packages/deluge/core/daemon.py", line 141, in __init__
    from deluge.core.core import Core
  File "/share/CACHEDEV1_DATA/.qpkg/Entware-ng/lib/python2.7/site-packages/deluge/core/core.py", line 36, in <module>
    from deluge._libtorrent import lt
  File "/share/CACHEDEV1_DATA/.qpkg/Entware-ng/lib/python2.7/site-packages/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: libboost_system.so.1.62.0: cannot open shared object file: No such file or directory
```
help please ...

**Comment by zyxmon** [comment]
Some time ago (in November 2016, not after the last update) the naming of some packages changed

boost*1_61_* was renamed boost*1.61.* and now it is updated to 1.62

You have 2 solutions.
1. Edit /opt/lib/opkg/status file and remove all boost blocks that have underscore.
Install boost libs that were installed with `opkg install boost-system` commands

2. Try the following
remove 1_61 packages with
`opkg remove boost-system --force-depends`
`opkg install boost-system`

If you are using Entware-ng and have a new kernel you can switch to Entware-3x that is more appropriate for the latest firmwares and devices. In this case yuo'll need to install from scratch.
