### ISSUE TITLE
deluge не запускается, т. к. хочет старую версию boost

### ISSUE THREAD

**Issue by ilya-fedin** [Entware-ng/Entware-ng#700]
deluge не запускается, т. к. зависит от rblibtorrent, который хочет boost версии 1.63.0, а в репозитории 1.64.0.
Вот трейс:
```
[ERROR   ] 22:29:02 main:248 libboost_system.so.1.63.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/deluge/main.py", line 241, in start_daemon
    Daemon(options, args)
  File "/opt/lib/python2.7/site-packages/deluge/core/daemon.py", line 144, in __init__
    from deluge.core.core import Core
  File "/opt/lib/python2.7/site-packages/deluge/core/core.py", line 38, in <module>
    from deluge._libtorrent import lt
  File "/opt/lib/python2.7/site-packages/deluge/_libtorrent.py", line 59, in <module>
    import libtorrent as lt
ImportError: libboost_system.so.1.63.0: cannot open shared object file: No such file or directory
```

**Comment by ryzhovau** [comment]
https://github.com/Entware-ng/Entware-ng/wiki#note-about-packages-upgrade
